export interface Task {
	chance: number;
	holdDuration?: number;
	score: number;
	color: Color3;
	text: string;
	willSound: boolean;
	soundID?: string;
	soundLooped?: boolean;
	soundVolume?: number;
	soundClient?: boolean;
	completedTime: number;
	timeSound?: number;
	enabled?: boolean;
}

declare const Bed: Task;
declare const Conditioner: Task;
declare const TV: Task;
declare const Dumbbells: Task;
declare const Shower: Task;
declare const Car: Task;
declare const Book: Task;
declare const Aquarium: Task;
declare const Letter: Task;
declare const Bear: Task;
declare const Guitar: Task;
declare const Closet: Task;
declare const Teeth: Task;
declare const Vase: Task;
declare const Radiator: Task;
declare const Radio: Task;
declare const Nap: Task;
declare const Alarm: Task;
declare const Sunglasses: Task;
declare const Rest: Task;
declare const Gift: Task;
declare const Candle: Task;
declare const Painting: Task;
declare const PaperPlane: Task;
declare const Jar: Task;
declare const Fan: Task;
declare const NewsPaper: Task;
declare const PetBowl: Task;
declare const Wash: Task;
declare const MailBox: Task;
declare const OpenWindows: Task;
declare const CloseWindows: Task;
declare const Poster: Task;
declare const Teleports: Task;
